// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createParent = `-- name: CreateParent :one
INSERT INTO parents (
    email,
    password_hash, 
    display_name, 
    marketing_opt_in
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, email, password_hash, display_name, marketing_opt_in, created_at, updated_at
`

type CreateParentParams struct {
	Email          string `db:"email" json:"email"`
	PasswordHash   string `db:"password_hash" json:"password_hash"`
	DisplayName    string `db:"display_name" json:"display_name"`
	MarketingOptIn bool   `db:"marketing_opt_in" json:"marketing_opt_in"`
}

func (q *Queries) CreateParent(ctx context.Context, arg CreateParentParams) (Parent, error) {
	row := q.db.QueryRow(ctx, createParent,
		arg.Email,
		arg.PasswordHash,
		arg.DisplayName,
		arg.MarketingOptIn,
	)
	var i Parent
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.MarketingOptIn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO auth_sessions (
    actor_type, 
    actor_id, 
    token_hash,
    device_id,
    expires_at
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, actor_type, actor_id, token_hash, device_id, expires_at, revoked_at, created_at
`

type CreateSessionParams struct {
	ActorType ActorType          `db:"actor_type" json:"actor_type"`
	ActorID   pgtype.UUID        `db:"actor_id" json:"actor_id"`
	TokenHash string             `db:"token_hash" json:"token_hash"`
	DeviceID  pgtype.Text        `db:"device_id" json:"device_id"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (AuthSession, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ActorType,
		arg.ActorID,
		arg.TokenHash,
		arg.DeviceID,
		arg.ExpiresAt,
	)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.ActorType,
		&i.ActorID,
		&i.TokenHash,
		&i.DeviceID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getParentByEmail = `-- name: GetParentByEmail :one
SELECT id, email, password_hash, display_name, marketing_opt_in, created_at, updated_at FROM parents 
WHERE email = $1 
LIMIT 1
`

func (q *Queries) GetParentByEmail(ctx context.Context, email string) (Parent, error) {
	row := q.db.QueryRow(ctx, getParentByEmail, email)
	var i Parent
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.MarketingOptIn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT id, actor_type, actor_id, token_hash, device_id, expires_at, revoked_at, created_at FROM auth_sessions
WHERE token_hash = $1
    AND revoked_at IS NULL
    AND expires_at > now()
LIMIT 1
`

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (AuthSession, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.ActorType,
		&i.ActorID,
		&i.TokenHash,
		&i.DeviceID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokeAllSessionsByActor = `-- name: RevokeAllSessionsByActor :exec
UPDATE auth_sessions
    SET revoked_at = now()
WHERE actor_type = $1
    AND actor_id = $2
    AND revoked_at IS NULL
`

type RevokeAllSessionsByActorParams struct {
	ActorType ActorType   `db:"actor_type" json:"actor_type"`
	ActorID   pgtype.UUID `db:"actor_id" json:"actor_id"`
}

func (q *Queries) RevokeAllSessionsByActor(ctx context.Context, arg RevokeAllSessionsByActorParams) error {
	_, err := q.db.Exec(ctx, revokeAllSessionsByActor, arg.ActorType, arg.ActorID)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE auth_sessions
  SET revoked_at = now()
WHERE token_hash = $1
`

func (q *Queries) RevokeSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeSession, tokenHash)
	return err
}
