// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package auth

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ActorType string

const (
	ActorTypeParent ActorType = "parent"
	ActorTypeKid    ActorType = "kid"
)

func (e *ActorType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ActorType(s)
	case string:
		*e = ActorType(s)
	default:
		return fmt.Errorf("unsupported scan type for ActorType: %T", src)
	}
	return nil
}

type NullActorType struct {
	ActorType ActorType `json:"actor_type"`
	Valid     bool      `json:"valid"` // Valid is true if ActorType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullActorType) Scan(value interface{}) error {
	if value == nil {
		ns.ActorType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ActorType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullActorType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ActorType), nil
}

type AuthSession struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	ActorType ActorType          `db:"actor_type" json:"actor_type"`
	ActorID   pgtype.UUID        `db:"actor_id" json:"actor_id"`
	TokenHash string             `db:"token_hash" json:"token_hash"`
	DeviceID  pgtype.Text        `db:"device_id" json:"device_id"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	RevokedAt pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Parent struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	Email          string             `db:"email" json:"email"`
	PasswordHash   string             `db:"password_hash" json:"password_hash"`
	DisplayName    string             `db:"display_name" json:"display_name"`
	MarketingOptIn bool               `db:"marketing_opt_in" json:"marketing_opt_in"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ParentGateAttempt struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	ParentID  pgtype.UUID        `db:"parent_id" json:"parent_id"`
	A         int32              `db:"a" json:"a"`
	B         int32              `db:"b" json:"b"`
	Submitted int32              `db:"submitted" json:"submitted"`
	Succeeded bool               `db:"succeeded" json:"succeeded"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}
